# Generated by Django 4.1.3 on 2022-12-13 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=250)),
                ('imagen', models.ImageField(null=True, upload_to='taller')),
                ('cupos', models.IntegerField()),
                ('curso', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('horario', models.TextField()),
                ('Instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='postulaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('direccion', models.TextField(max_length=250)),
                ('villa', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('Taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.taller')),
            ],
        ),
    ]
