# Generated by Django 4.1.3 on 2022-12-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_taller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='fecha_ingresado',
        ),
        migrations.AlterField(
            model_name='taller',
            name='descripcion',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='taller',
            name='imagen',
            field=models.ImageField(null=True, upload_to='taller'),
        ),
    ]
