# Generated by Django 4.1.3 on 2022-12-11 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_instructor_password_remove_taller_fecha_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
