# Generated by Django 4.1.3 on 2022-12-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='cupos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
